### ISSUE TITLE
a newbie question

### ISSUE THREAD

**Issue by zeroknow** [Shougo/shougo-s-github#1]
Hi Shougo,
I started learning vim several days ago and am trying your nice dotvim setup.
After installing it, I got these errors when starting up. I can't solve it with Google, could you please give me some clues?
Thank you very much.
(The vim version I've got is 7.0. )
eskk.vim: warning: Your Vim is too old. Please use 7.3.32 at least.
Error detected while processing function altercmd#define..<SNR>27_do_define:
line   37:
E492: Not an editor command: Cnoreabbrev <expr> cd (getline(".") ==# 'cd') ? '' : 'cd'
E492: Not an editor command: Dnoreabbrev <expr> cd (getline(".") ==# 'cd') ? '' : 'cd'
E492: Not an editor command: Unoreabbrev <expr> uniq (getline(".") ==# 'uniq') ? '' : 'uniq'
E492: Not an editor command: nnoreabbrev <expr> uniq (getline(".") ==# 'uniq') ? '' : 'uniq'
E492: Not an editor command: qnoreabbrev <expr> uniq (getline(".") ==# 'uniq') ? '' : 'uniq'
Error detected while processing /misc/users/haosh/.vim/bundle/vundle/neocomplcache/plugin/neocomplcache.vim:
line   65:
g:neocomplcache_enable_quick_match option does not work this version of neocomplcache.
Error detected while processing /misc/users/haosh/.vim/bundle/vundle/unite.vim/plugin/unite.vim:
line   37:
g:unite_cd_command option does not work this version of unite.vim.
line   40:
g:unite_lcd_command option does not work this version of unite.vim.
Error detected while processing /misc/users/haosh/.vim/bundle/vundle/vim-metarw/plugin/metarw.vim:
line   39:
E216: No such group or event: SourceCmd ??_:{_,_/_}  call metarw#_event_handler('SourceCmd')
Error detected while processing /misc/users/haosh/.vim/bundle/vundle/operator-html-escape.vim/plugin/operator/html_escape.vim:
line   16:
E117: Unknown function: operator#user#define
line   17:
E117: Unknown function: operator#user#define
Error detected while processing /misc/users/haosh/.vim/bundle/vundle/VimClojure/autoload/vimclojure.vim:
line  318:
E475: Invalid argument: 11
line  345:
E475: Invalid argument: 13
line  385:
E475: Invalid argument: 13
line  392:
E475: Invalid argument: 18
line  714:
E475: Invalid argument: 11
line  723:
E475: Invalid argument: 13
Press ENTER or type command to continue

**Comment by Shougo** [comment]
OH, you shouldn't use my .vimrc.
My .vimrc depends on the many plugins.

**Comment by Shougo** [comment]
> (The vim version I've got is 7.0. )

Most of plugins is not supported Vim 7.0.

**Comment by Shougo** [comment]
I updated .vimrc.

**Comment by zeroknow** [comment]
Thanks. What does "updated" mean? Can it be used? Do you have any recommendation of a nice dotvim for a layman who doesn't know much about vim but wants to use the nice functions? Thank you very much:-)

**Comment by Shougo** [comment]
> Thanks. What does "updated" mean? Can it be used?

I updated shougo-s-github .vimrc. This .vimrc is same to latest my .vimrc.

> Do you have any recommendation of a nice dotvim for a layman who doesn't know much about vim but wants to use the nice functions?

I recomend you use a part of .vimrc  even if based on any .vimrc.
