### ISSUE TITLE
Suggestion: Loop of ~/.vim/rc/plugins/*

### ISSUE THREAD

**Issue by coresh** [Shougo/shougo-s-github#2]
Dear Shougo,

Regarding: ~/.vim/rc/plugins.rc.vim

What about loop (for i in ...) of all existed files at:
~/.vim/rc/plugins/*
like:

```
for i in // ~/.vim/rc/plugins/*
  if neobundle#tap('neocomplete.vim') "{{{
    let g:neocomplete#enable_at_startup = 1
    let neobundle#hooks.on_source =
        \ '~/.vim/rc/plugins/FILE_NAME'

    call neobundle#untap()
  endif "}}}
endfor
```

**Comment by Shougo** [comment]
No.  Why do you think you can use it?
Please read the code.  It cannot convert to the loop.

**Comment by Shougo** [comment]
But if you can convert to the loop, it is good.

**Comment by coresh** [comment]
Re: "But if you can convert to the loop, it is good."
Not sure: at current time.
Thanks for your quick reply and GREAT! action

**Comment by Shougo** [comment]
Pull request is wellcome.
