### ISSUE TITLE
LICENSE

### ISSUE THREAD

**Issue by tony** [Shougo/shougo-s-github#4]
Can you add MIT license so we can take snippets?

**Comment by Shougo** [comment]
Unfortunatelly, I cannot decide the LICENSE.
Because, it contains some of copy-paste lines and dictionary files.

Plugin configurations are made by mine.

**Comment by tony** [comment]
Is this safe? MIT? https://github.com/Shougo/shougo-s-github/blob/master/vim/rc/plugins/neocomplete.rc.vim

**Comment by Shougo** [comment]
It is MIT in the directory.

https://github.com/Shougo/shougo-s-github/tree/master/vim/rc/plugins

**Comment by tony** [comment]
Thank you!
