### ISSUE TITLE
Plugin autocmd set before `dein#end()` is called

### ISSUE THREAD

**Issue by ClaudiaJ** [Shougo/shougo-s-github#5]
In dein.txt you write the following for the `User#dein#source` hook:

> Note: You must set the autocmd before `dein#end()`.

Your `plugins.rc.vim` where your hooks are defined is sourced after `dein#end()` is called in `dein.rc.vim`, and you do not manually call `dein#call_hook('source')`

How, if at all, are your hooks being called to configure your plugins?

**Comment by Shougo** [comment]
Yes, because I don't use the hook feature for non lazy loaded plugins.
So, no problem for me.
